export { createEnvironmentRegistry } from "./src/environment-registry.js"
export { defineType } from "./src/type-def.js"

export type { EnvironmentRegistry } from "./src/environment-registry.js"
export type { VariableRegistry } from "./src/variable-registry.js"
export type { Resolver } from "./src/resolver.js"
export type { Environment } from "./src/environment.js"
export type { Variable } from "./src/variable.js"
export type { TypeDef, Infer } from "./src/type-def.js"
export type { Resolution } from "./src/resolution.js"
